//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class IncendiosForestales
    {
        public int ID { get; set; }
        public Nullable<int> IdBosques { get; set; }
        public Nullable<int> IdPersonal { get; set; }
        public Nullable<int> IdReservasAgua { get; set; }
        public Nullable<int> IdHerramientas { get; set; }
        public Nullable<int> IdCantidadHerramienta { get; set; }
    }
}
