//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ReservasAgua
    {
        public int ID { get; set; }
        public string Nombre { get; set; }
        public Nullable<int> Area { get; set; }
        public string TipoReserva { get; set; }
        public string Ubicacion { get; set; }
    }
}
